### ISSUE TITLE
Firmware download from update.wifiradio.com fails

### ISSUE THREAD

**Issue by SurmanPP** [MatrixEditor/frontier-smart-api#7]
`python3 -m fsapi isu --find --collect myFile 192.168.178.106 --verbose` fails with `Unexpected result code: 404` opening the download link(`https://update.wifiradiofrontier.com/Update.aspx?f=/updates/ir-cui-FS2340-0000-0013.4.5.10.46f70b-1A30.isu.bin`) in a browser seems to return 404 too.

Some things I have noticed are that the link does not contain the version like described in #1, there is also an error about an malformed MAC-Address(30:58:90:5f:d4:47) and in the webinterface the update section wants a .sap.bin called "SoftAP update file" instead of .isu.bin file.

**Comment by SurmanPP** [comment]
Let me correct I just ran `python3 -m fsapi isu --file ./bin/updates.txt --verbose` and all update.wifiradio.com links failed and some nuv-isu-cdn.azureedge.net links too.

**Comment by MatrixEditor** [comment]
As the MAC, firmware version and customisation are not required when fetching the update file, they are not passed to the final url. All "updates" stored in the [updates.txt](https://github.com/MatrixEditor/frontier-smart-api/blob/main/bin/updates.txt) file have been collected from external websites and are **not** validated. Therefore, running the command above could cause the issue you've described. All known updates are located in the [known-versions.txt](https://github.com/MatrixEditor/frontier-smart-api/blob/main/bin/known-versions.txt) - the command should work here.

Next, the `*.sap.bin` update file is not directly available and can be requested on the radio's/device's manufacturer.

**Comment by SurmanPP** [comment]
Great! It works now. 🥳
